name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: |
          cd app/sample-spring-boot-app/sample-app
          mvn clean test package

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/spring-app:${{ github.sha }} -f docker/Dockerfile .

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/spring-app:${{ github.sha }}

      - name: Deploy to Dev
        run: |
          echo "Deployment to Dev namespace via kubectl"
